@echo off
echo Setting up Vercel environment variables...

echo Adding NEXT_PUBLIC_SUPABASE_URL...
echo https://fweeyjnqwxywmpmnqpts.supabase.co | vercel env add NEXT_PUBLIC_SUPABASE_URL production

echo Adding NEXT_PUBLIC_SUPABASE_ANON_KEY...
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3ZWV5am5xd3h5d21wbW5xcHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzU2OTQsImV4cCI6MjA3MTc1MTY5NH0.-vLqNDwbpA3zpJh45VFB5Oo2ehnBdLaLlNMDi1o75m4 | vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production

echo Adding SUPABASE_SERVICE_KEY...
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3ZWV5am5xd3h5d21wbW5xcHRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjE3NTY5NCwiZXhwIjoyMDcxNzUxNjk0fQ.NnmkVFRPZ5iW-gwYYQSBPouSpWgkn0XZyjhcY9__zLE | vercel env add SUPABASE_SERVICE_KEY production

echo Adding EMAIL_USER...
echo jayvalleo@sweetdreamsmusic.com | vercel env add EMAIL_USER production

echo Adding EMAIL_PASS...
echo yxrt acci xhay sxtp | vercel env add EMAIL_PASS production

echo Adding ADMIN_PASSWORD_HASH...
echo $2b$12$rfoN8h9GsZ3oWnbd9J/yeeY0GKeaT38p9Xgk.KpuHE2Vmjw2TEGVG | vercel env add ADMIN_PASSWORD_HASH production

echo Adding CLOUDFLARE_ACCOUNT_ID...
echo 930f31024174032bfcbbb01ca4e88215 | vercel env add CLOUDFLARE_ACCOUNT_ID production

echo Adding CLOUDFLARE_STREAM_API_TOKEN...
echo CVZM0_55KzdK6EwuLM_gz7C-Yd2jTlZqBRQwvSJQ | vercel env add CLOUDFLARE_STREAM_API_TOKEN production

echo Environment variables setup complete!
pause